apiVersion: operator.kyma-project.io/v1alpha1
kind: ApplicationConnector
metadata:
  namespace: kyma-system
  labels:
    kyma-project.io/module: application-connector
    app.kubernetes.io/name: applicationconnector
    app.kubernetes.io/instance: applicationconnector-sample
    app.kubernetes.io/part-of: application-connector-manager
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: application-connector-manager
  name: applicationconnector-sample
spec: {}
