name: ACM

on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - .github/workflows/acm.yaml
      - main.go
      - api/**
      - pkg/**
      - controllers/**
      - application-connector.yaml
      - application-connector-dependencies.yaml
      - go.sum
      - go.mod
      - Dockerfile

  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflows/acm.yaml
      - main.go
      - api/**
      - pkg/**
      - controllers/**
      - application-connector.yaml
      - application-connector-dependencies.yaml
      - go.sum
      - go.mod
      - Dockerfile

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  setup-and-tests:
    uses: ./.github/workflows/controller/tests.yaml

  build-image:
    needs: setup-and-tests
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: application-connector-manager
      dockerfile: Dockerfile
      context: .
      tags: |
        ${{ needs.setup-and-tests.outputs.latest }}

  print-images:
    runs-on: ubuntu-latest
    needs: [build-image]
    steps:
      - name: "Generate summary"
        run: |
          {
            echo '## ACM Images'
            printf '\n```json\n'
            echo '${{ needs.build-image.outputs.images }}' | jq
            printf '\n```\n'
          } >> $GITHUB_STEP_SUMMARY
