apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kyma-project.io--acm-validator-allow-to-eventing
  namespace: system
spec:
  podSelector:
    matchLabels:
      app: central-application-connectivity-validator
  policyTypes:
    - Egress
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kyma-system
        podSelector:
          matchLabels:
            app.kubernetes.io/name: eventing-publisher-proxy
