apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kyma-project.io--acm-module-allow-from-sidecar
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - application-connector-manager
          - compass-runtime-agent
          - central-application-gateway
          - central-application-connectivity-validator
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 15010
        - protocol: TCP
          port: 15012
        - protocol: TCP
          port: 15017
        - protocol: TCP
          port: 15014
        - protocol: TCP
          port: 15021
        - protocol: TCP
          port: 15090
