kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: kyma-project.io--acm-module-allow-metrics
  namespace: system
  labels:
    app.kubernetes.io/name: acm-controller
    app.kubernetes.io/managed-by: kustomize
    purpose: acm-metrics-scraping
spec:
  podSelector:
    matchLabels:
      app: application-connector-manager
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
      from:
        - podSelector:
            matchLabels:
              networking.kyma-project.io/metrics-scraping: allowed
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kyma-system
  policyTypes:
    - Ingress
